use crate::Scalar;
use crate::tensor::{Matrix3, Point3, Vector3};
use crate::units::angle::{Angle, AngleUnit, Radian};
use crate::units::length::{Angstrom, Length, LengthUnit};
use crate::units::reciprocal_length::{ReciprocalAngstrom, ReciprocalLength, ReciprocalLengthUnit};
use crate::units::reciprocal_volume::{
    ReciprocalCubicAngstrom, ReciprocalVolume, ReciprocalVolumeUnit,
};
use crate::units::volume::{CubicAngstrom, Volume, VolumeUnit};

/// A periodic lattice: the discrete group of translations generated by three
/// basis vectors **a**, **b**, **c**, together with the quotient of space it
/// induces.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Lattice<V> {
    basis: Matrix3<V>,
    reduced: Matrix3<V>,
}

/// The reciprocal lattice: the dual basis **a\***, **b\***, **c\*** of a
/// [`Lattice`], satisfying **a**ᵢ · **a\***ⱼ = δᵢⱼ.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ReciprocalLattice<V> {
    basis: Matrix3<V>,
    reduced: Matrix3<V>,
}

impl<V: Scalar> Lattice<V> {
    /// Wraps `basis` (columns are lattice vectors in ångströms) together with
    /// its reduced form, returning `None` if the matrix is degenerate (zero or
    /// non-finite volume).
    #[inline]
    fn from_basis(basis: Matrix3<V>) -> Option<Self> {
        let (basis, reduced) = basis::prepare(basis)?;
        Some(Self { basis, reduced })
    }

    /// Constructs a lattice from its three basis vectors, returning `None` if
    /// they are coplanar (zero enclosed volume).
    #[inline]
    pub fn from_vectors<U: LengthUnit>(
        a: Vector3<Length<V, U>>,
        b: Vector3<Length<V, U>>,
        c: Vector3<Length<V, U>>,
    ) -> Option<Self> {
        Self::from_basis(Matrix3::from_cols(
            a.map(into_angstroms),
            b.map(into_angstroms),
            c.map(into_angstroms),
        ))
    }

    /// Constructs a cubic lattice with edge length `side`, returning `None` if
    /// `side` is not strictly positive and finite.
    #[inline]
    pub fn cubic<U: LengthUnit>(side: Length<V, U>) -> Option<Self> {
        let side = into_angstroms(side);
        if !positive(side) {
            return None;
        }
        Self::from_basis(Matrix3::from_diagonal(Vector3::splat(side)))
    }

    /// Constructs an orthorhombic (axis-aligned) lattice from its three edge
    /// lengths, returning `None` if any length is not strictly positive and
    /// finite.
    #[inline]
    pub fn orthorhombic<U: LengthUnit>(
        a: Length<V, U>,
        b: Length<V, U>,
        c: Length<V, U>,
    ) -> Option<Self> {
        let (a, b, c) = (into_angstroms(a), into_angstroms(b), into_angstroms(c));
        if !(positive(a) && positive(b) && positive(c)) {
            return None;
        }
        Self::from_basis(Matrix3::from_diagonal(Vector3::new(a, b, c)))
    }

    /// Constructs a lattice from the crystallographic parameters: edge lengths
    /// `a`, `b`, `c` and inter-edge angles `alpha` (∠**b**,**c**), `beta`
    /// (∠**a**,**c**), `gamma` (∠**a**,**b**).
    ///
    /// **a** is placed along the `x` axis and **b** in the `xy` plane
    /// (standard crystallographic orientation). Returns `None` if any edge
    /// length is not strictly positive and finite, or if the parameters
    /// describe no realizable cell (inconsistent angles or degenerate
    /// volume).
    #[inline]
    pub fn from_parameters<L: LengthUnit, A: AngleUnit>(
        a: Length<V, L>,
        b: Length<V, L>,
        c: Length<V, L>,
        alpha: Angle<V, A>,
        beta: Angle<V, A>,
        gamma: Angle<V, A>,
    ) -> Option<Self> {
        let (a, b, c) = (into_angstroms(a), into_angstroms(b), into_angstroms(c));
        if !(positive(a) && positive(b) && positive(c)) {
            return None;
        }
        Self::from_basis(basis::from_parameters(
            a,
            b,
            c,
            into_radians(alpha),
            into_radians(beta),
            into_radians(gamma),
        ))
    }

    /// Returns the first lattice vector **a**, in unit `U`.
    #[inline]
    pub fn a<U: LengthUnit>(&self) -> Vector3<Length<V, U>> {
        self.basis.col(0).map(from_angstroms)
    }

    /// Returns the second lattice vector **b**, in unit `U`.
    #[inline]
    pub fn b<U: LengthUnit>(&self) -> Vector3<Length<V, U>> {
        self.basis.col(1).map(from_angstroms)
    }

    /// Returns the third lattice vector **c**, in unit `U`.
    #[inline]
    pub fn c<U: LengthUnit>(&self) -> Vector3<Length<V, U>> {
        self.basis.col(2).map(from_angstroms)
    }

    /// Returns the three edge lengths `(|a|, |b|, |c|)`, in unit `U`.
    #[inline]
    pub fn edge_lengths<U: LengthUnit>(&self) -> Vector3<Length<V, U>> {
        basis::edge_lengths(self.basis).map(from_angstroms)
    }

    /// Returns the three inter-edge angles `(α, β, γ)` — ∠(**b**,**c**),
    /// ∠(**a**,**c**), ∠(**a**,**b**) — in unit `U`.
    #[inline]
    pub fn angles<U: AngleUnit>(&self) -> Vector3<Angle<V, U>> {
        basis::angles(self.basis).map(from_radians)
    }

    /// Returns the enclosed volume `|det(basis)|`, in unit `U`.
    #[inline]
    pub fn volume<U: VolumeUnit>(&self) -> Volume<V, U> {
        Volume::<V, CubicAngstrom>::new(basis::volume(self.basis)).to::<U>()
    }

    /// Maps a fractional coordinate to its Cartesian position `r = basis · f`,
    /// in unit `U`.
    #[inline]
    pub fn to_cartesian<U: LengthUnit>(&self, fractional: Point3<V>) -> Point3<Length<V, U>> {
        Point3::from_vector((self.basis * fractional.to_vector()).map(from_angstroms))
    }

    /// Maps a Cartesian position to its (dimensionless) fractional coordinate
    /// `f = basis⁻¹ · r`.
    #[inline]
    pub fn to_fractional<U: LengthUnit>(&self, cartesian: Point3<Length<V, U>>) -> Point3<V> {
        Point3::from_vector(self.basis.inverse() * cartesian.to_vector().map(into_angstroms))
    }

    /// Returns the image of `position` inside the cell — the representative
    /// whose fractional coordinates lie in `[0, 1)` — in unit `U`.
    #[inline]
    pub fn wrap<U: LengthUnit>(&self, position: Point3<Length<V, U>>) -> Point3<Length<V, U>> {
        let folded = basis::fold(self.basis, position.to_vector().map(into_angstroms));
        Point3::from_vector(folded.map(from_angstroms))
    }

    /// Returns the shortest representative of `displacement` modulo the
    /// lattice, in unit `U`.
    ///
    /// Exact for any cell, however oblique the basis presenting it; images
    /// exactly half a lattice vector apart resolve deterministically.
    #[inline]
    pub fn minimum_image<U: LengthUnit>(
        &self,
        displacement: Vector3<Length<V, U>>,
    ) -> Vector3<Length<V, U>> {
        basis::nearest(self.reduced, displacement.map(into_angstroms)).map(from_angstroms)
    }

    /// Iterates the lattice translations no longer than `radius`, the zero
    /// vector included, in unit `U`.
    ///
    /// Yielded in ascending order of their coefficients over the reduced
    /// basis; the count grows with the cube of the radius.
    #[inline]
    pub fn translations<U: LengthUnit>(
        self,
        radius: Length<V, U>,
    ) -> impl Iterator<Item = Vector3<Length<V, U>>> {
        basis::points(self.reduced, into_angstroms(radius)).map(|point| point.map(from_angstroms))
    }

    /// Returns the same lattice on a Minkowski-reduced basis, whose edge
    /// lengths are the lattice's successive minima λ₁ ≤ λ₂ ≤ λ₃.
    #[inline]
    pub fn reduced(&self) -> Self {
        Self {
            basis: self.reduced,
            reduced: self.reduced,
        }
    }

    /// Returns the dual [`ReciprocalLattice`], whose basis **a\***, **b\***,
    /// **c\*** satisfies **a**ᵢ · **a\***ⱼ = δᵢⱼ — with no factor of 2π.
    ///
    /// # Panics
    ///
    /// Panics if the dual basis is not representable, reachable only for a
    /// cell so ill-conditioned that inverting it overflows.
    #[inline]
    pub fn reciprocal(&self) -> ReciprocalLattice<V> {
        ReciprocalLattice::from_basis(basis::dual(self.basis)).expect("dual basis is representable")
    }
}

impl<V: Scalar> ReciprocalLattice<V> {
    /// Wraps `basis` (columns are reciprocal lattice vectors in reciprocal
    /// ångströms) together with its reduced form, returning `None` if the
    /// matrix is degenerate (zero or non-finite volume).
    #[inline]
    fn from_basis(basis: Matrix3<V>) -> Option<Self> {
        let (basis, reduced) = basis::prepare(basis)?;
        Some(Self { basis, reduced })
    }

    /// Constructs a reciprocal lattice from its three basis vectors, returning
    /// `None` if they are coplanar (zero enclosed volume).
    #[inline]
    pub fn from_vectors<U: ReciprocalLengthUnit>(
        a: Vector3<ReciprocalLength<V, U>>,
        b: Vector3<ReciprocalLength<V, U>>,
        c: Vector3<ReciprocalLength<V, U>>,
    ) -> Option<Self> {
        Self::from_basis(Matrix3::from_cols(
            a.map(into_reciprocal_angstroms),
            b.map(into_reciprocal_angstroms),
            c.map(into_reciprocal_angstroms),
        ))
    }

    /// Constructs a cubic reciprocal lattice with edge length `side`,
    /// returning `None` if `side` is not strictly positive and finite.
    #[inline]
    pub fn cubic<U: ReciprocalLengthUnit>(side: ReciprocalLength<V, U>) -> Option<Self> {
        let side = into_reciprocal_angstroms(side);
        if !positive(side) {
            return None;
        }
        Self::from_basis(Matrix3::from_diagonal(Vector3::splat(side)))
    }

    /// Constructs an orthorhombic (axis-aligned) reciprocal lattice from its
    /// three edge lengths, returning `None` if any length is not strictly
    /// positive and finite.
    #[inline]
    pub fn orthorhombic<U: ReciprocalLengthUnit>(
        a: ReciprocalLength<V, U>,
        b: ReciprocalLength<V, U>,
        c: ReciprocalLength<V, U>,
    ) -> Option<Self> {
        let a = into_reciprocal_angstroms(a);
        let b = into_reciprocal_angstroms(b);
        let c = into_reciprocal_angstroms(c);
        if !(positive(a) && positive(b) && positive(c)) {
            return None;
        }
        Self::from_basis(Matrix3::from_diagonal(Vector3::new(a, b, c)))
    }

    /// Constructs a reciprocal lattice from the reciprocal cell parameters:
    /// edge lengths `a`, `b`, `c` and inter-edge angles `alpha`
    /// (∠**b\***,**c\***), `beta` (∠**a\***,**c\***), `gamma`
    /// (∠**a\***,**b\***).
    ///
    /// **a\*** is placed along the `x` axis and **b\*** in the `xy` plane.
    /// Returns `None` if any edge length is not strictly positive and finite,
    /// or if the parameters describe no realizable cell (inconsistent angles
    /// or degenerate volume).
    #[inline]
    pub fn from_parameters<R: ReciprocalLengthUnit, A: AngleUnit>(
        a: ReciprocalLength<V, R>,
        b: ReciprocalLength<V, R>,
        c: ReciprocalLength<V, R>,
        alpha: Angle<V, A>,
        beta: Angle<V, A>,
        gamma: Angle<V, A>,
    ) -> Option<Self> {
        let a = into_reciprocal_angstroms(a);
        let b = into_reciprocal_angstroms(b);
        let c = into_reciprocal_angstroms(c);
        if !(positive(a) && positive(b) && positive(c)) {
            return None;
        }
        Self::from_basis(basis::from_parameters(
            a,
            b,
            c,
            into_radians(alpha),
            into_radians(beta),
            into_radians(gamma),
        ))
    }

    /// Returns the first reciprocal lattice vector **a\***, in unit `U`.
    #[inline]
    pub fn a<U: ReciprocalLengthUnit>(&self) -> Vector3<ReciprocalLength<V, U>> {
        self.basis.col(0).map(from_reciprocal_angstroms)
    }

    /// Returns the second reciprocal lattice vector **b\***, in unit `U`.
    #[inline]
    pub fn b<U: ReciprocalLengthUnit>(&self) -> Vector3<ReciprocalLength<V, U>> {
        self.basis.col(1).map(from_reciprocal_angstroms)
    }

    /// Returns the third reciprocal lattice vector **c\***, in unit `U`.
    #[inline]
    pub fn c<U: ReciprocalLengthUnit>(&self) -> Vector3<ReciprocalLength<V, U>> {
        self.basis.col(2).map(from_reciprocal_angstroms)
    }

    /// Returns the three edge lengths `(|a*|, |b*|, |c*|)` — the reciprocals
    /// of the spacings between the primary lattice planes — in unit `U`.
    #[inline]
    pub fn edge_lengths<U: ReciprocalLengthUnit>(&self) -> Vector3<ReciprocalLength<V, U>> {
        basis::edge_lengths(self.basis).map(from_reciprocal_angstroms)
    }

    /// Returns the three inter-edge angles `(α*, β*, γ*)` —
    /// ∠(**b\***,**c\***), ∠(**a\***,**c\***), ∠(**a\***,**b\***) — in unit
    /// `U`.
    #[inline]
    pub fn angles<U: AngleUnit>(&self) -> Vector3<Angle<V, U>> {
        basis::angles(self.basis).map(from_radians)
    }

    /// Returns the enclosed volume `|det(basis)|` — the reciprocal of the
    /// direct cell's — in unit `U`.
    #[inline]
    pub fn volume<U: ReciprocalVolumeUnit>(&self) -> ReciprocalVolume<V, U> {
        ReciprocalVolume::<V, ReciprocalCubicAngstrom>::new(basis::volume(self.basis)).to::<U>()
    }

    /// Maps Miller indices to their wavevector `k = basis · (h, k, l)`, in
    /// unit `U`.
    #[inline]
    pub fn to_cartesian<U: ReciprocalLengthUnit>(
        &self,
        indices: Point3<V>,
    ) -> Point3<ReciprocalLength<V, U>> {
        Point3::from_vector((self.basis * indices.to_vector()).map(from_reciprocal_angstroms))
    }

    /// Maps a wavevector to its (dimensionless) Miller indices
    /// `(h, k, l) = basis⁻¹ · k`.
    #[inline]
    pub fn to_fractional<U: ReciprocalLengthUnit>(
        &self,
        wavevector: Point3<ReciprocalLength<V, U>>,
    ) -> Point3<V> {
        Point3::from_vector(
            self.basis.inverse() * wavevector.to_vector().map(into_reciprocal_angstroms),
        )
    }

    /// Returns the image of `wavevector` inside the reciprocal cell — the
    /// representative whose Miller indices lie in `[0, 1)` — in unit `U`.
    #[inline]
    pub fn wrap<U: ReciprocalLengthUnit>(
        &self,
        wavevector: Point3<ReciprocalLength<V, U>>,
    ) -> Point3<ReciprocalLength<V, U>> {
        let folded = basis::fold(
            self.basis,
            wavevector.to_vector().map(into_reciprocal_angstroms),
        );
        Point3::from_vector(folded.map(from_reciprocal_angstroms))
    }

    /// Returns the shortest representative of `displacement` modulo the
    /// reciprocal lattice — its image in the first Brillouin zone — in unit
    /// `U`.
    ///
    /// Exact for any cell, however oblique the basis presenting it; images
    /// exactly half a lattice vector apart resolve deterministically.
    #[inline]
    pub fn minimum_image<U: ReciprocalLengthUnit>(
        &self,
        displacement: Vector3<ReciprocalLength<V, U>>,
    ) -> Vector3<ReciprocalLength<V, U>> {
        basis::nearest(self.reduced, displacement.map(into_reciprocal_angstroms))
            .map(from_reciprocal_angstroms)
    }

    /// Iterates the reciprocal lattice vectors no longer than `radius`, the
    /// zero vector included, in unit `U` — the terms of a reciprocal-space
    /// sum.
    ///
    /// Yielded in ascending order of their coefficients over the reduced
    /// basis; the count grows with the cube of the radius.
    #[inline]
    pub fn translations<U: ReciprocalLengthUnit>(
        self,
        radius: ReciprocalLength<V, U>,
    ) -> impl Iterator<Item = Vector3<ReciprocalLength<V, U>>> {
        basis::points(self.reduced, into_reciprocal_angstroms(radius))
            .map(|point| point.map(from_reciprocal_angstroms))
    }

    /// Returns the same reciprocal lattice on a Minkowski-reduced basis, whose
    /// edge lengths are its successive minima λ₁ ≤ λ₂ ≤ λ₃.
    #[inline]
    pub fn reduced(&self) -> Self {
        Self {
            basis: self.reduced,
            reduced: self.reduced,
        }
    }

    /// Returns the dual [`Lattice`], recovering the lattice this one is the
    /// reciprocal of.
    ///
    /// # Panics
    ///
    /// Panics if the dual basis is not representable, reachable only for a
    /// cell so ill-conditioned that inverting it overflows.
    #[inline]
    pub fn reciprocal(&self) -> Lattice<V> {
        Lattice::from_basis(basis::dual(self.basis)).expect("dual basis is representable")
    }
}

/// Returns whether `value` is a usable edge length: strictly positive and
/// finite.
#[inline]
fn positive<V: Scalar>(value: V) -> bool {
    value > V::ZERO && value.is_finite()
}

/// Converts a length to its bare scalar value in ångströms.
#[inline]
fn into_angstroms<V: Scalar, U: LengthUnit>(length: Length<V, U>) -> V {
    length.to::<Angstrom>().value()
}

/// Wraps a bare ångström scalar as a length in unit `U`.
#[inline]
fn from_angstroms<V: Scalar, U: LengthUnit>(value: V) -> Length<V, U> {
    Length::<V, Angstrom>::new(value).to::<U>()
}

/// Converts a reciprocal length to its bare scalar value in reciprocal
/// ångströms.
#[inline]
fn into_reciprocal_angstroms<V: Scalar, U: ReciprocalLengthUnit>(
    length: ReciprocalLength<V, U>,
) -> V {
    length.to::<ReciprocalAngstrom>().value()
}

/// Wraps a bare reciprocal ångström scalar as a reciprocal length in unit `U`.
#[inline]
fn from_reciprocal_angstroms<V: Scalar, U: ReciprocalLengthUnit>(
    value: V,
) -> ReciprocalLength<V, U> {
    ReciprocalLength::<V, ReciprocalAngstrom>::new(value).to::<U>()
}

/// Converts an angle to its bare scalar value in radians.
#[inline]
fn into_radians<V: Scalar, A: AngleUnit>(angle: Angle<V, A>) -> V {
    angle.to::<Radian>().value()
}

/// Wraps a bare radian scalar as an angle in unit `U`.
#[inline]
fn from_radians<V: Scalar, U: AngleUnit>(value: V) -> Angle<V, U> {
    Angle::<V, Radian>::new(value).to::<U>()
}

/// Lattice arithmetic over a basis of bare scalars in canonical units.
///
/// Every item here is blind to dimension: the two lattice types differ only in
/// the units they cross at their surface, and share this engine underneath.
mod basis {
    use crate::Scalar;
    use crate::tensor::{Matrix3, Vector3};

    /// Pairs `basis` with its reduced form, returning `None` if either is
    /// degenerate (zero or non-finite volume).
    ///
    /// Reducing is what the quotient operations run over, so a cell too thin
    /// for its own squared extents to survive — which leaves the reduction
    /// without a finite answer — is refused here rather than carried.
    pub(super) fn prepare<V: Scalar>(basis: Matrix3<V>) -> Option<(Matrix3<V>, Matrix3<V>)> {
        if !basis.is_invertible() {
            return None;
        }
        let reduced = reduce(basis);
        reduced.is_invertible().then_some((basis, reduced))
    }

    /// Returns the basis a cell of the given edge lengths and inter-edge
    /// angles (in radians) encloses, with the first vector along `x` and the
    /// second in the `xy` plane.
    ///
    /// Parameters describing no realizable cell yield a non-finite basis,
    /// which [`prepare`] rejects.
    pub(super) fn from_parameters<V: Scalar>(
        a: V,
        b: V,
        c: V,
        alpha: V,
        beta: V,
        gamma: V,
    ) -> Matrix3<V> {
        let (_, cos_alpha) = alpha.sin_cos();
        let (_, cos_beta) = beta.sin_cos();
        let (sin_gamma, cos_gamma) = gamma.sin_cos();
        let x = c * cos_beta;
        let y = c * (cos_alpha - cos_beta * cos_gamma) / sin_gamma;
        let z = c
            * (V::ONE - cos_alpha * cos_alpha - cos_beta * cos_beta - cos_gamma * cos_gamma
                + V::from_f64(2.0) * cos_alpha * cos_beta * cos_gamma)
                .sqrt()
            / sin_gamma;
        Matrix3::from_cols(
            Vector3::new(a, V::ZERO, V::ZERO),
            Vector3::new(b * cos_gamma, b * sin_gamma, V::ZERO),
            Vector3::new(x, y, z),
        )
    }

    /// Returns the three edge lengths of `basis`.
    pub(super) fn edge_lengths<V: Scalar>(basis: Matrix3<V>) -> Vector3<V> {
        Vector3::new(
            basis.col(0).norm(),
            basis.col(1).norm(),
            basis.col(2).norm(),
        )
    }

    /// Returns the three inter-edge angles of `basis`, in radians.
    pub(super) fn angles<V: Scalar>(basis: Matrix3<V>) -> Vector3<V> {
        let (a, b, c) = (basis.col(0), basis.col(1), basis.col(2));
        Vector3::new(b.angle_between(c), a.angle_between(c), a.angle_between(b))
    }

    /// Returns the volume `basis` encloses.
    pub(super) fn volume<V: Scalar>(basis: Matrix3<V>) -> V {
        basis.determinant().abs()
    }

    /// Returns the perpendicular distances between the three pairs of opposite
    /// cell faces, which bound each coefficient of a translation of a given
    /// length.
    pub(super) fn widths<V: Scalar>(basis: Matrix3<V>) -> Vector3<V> {
        let enclosed = volume(basis);
        let (a, b, c) = (basis.col(0), basis.col(1), basis.col(2));
        Vector3::new(
            enclosed / b.cross(c).norm(),
            enclosed / c.cross(a).norm(),
            enclosed / a.cross(b).norm(),
        )
    }

    /// Returns the dual of `basis`, the transposed inverse whose columns pair
    /// with the originals as `aᵢ · a*ⱼ = δᵢⱼ`.
    pub(super) fn dual<V: Scalar>(basis: Matrix3<V>) -> Matrix3<V> {
        basis.inverse().transpose()
    }

    /// Returns the image of `position` whose coefficients over `basis` lie in
    /// `[0, 1)`.
    ///
    /// A coefficient a hair below zero rounds to exactly one under the
    /// euclidean remainder, which the far edge of the cell shares with its
    /// origin; taking the origin keeps the half-open interval closed. Only a
    /// coefficient at or past that edge is moved, so a position that is not
    /// finite stays that way instead of folding onto the origin.
    pub(super) fn fold<V: Scalar>(basis: Matrix3<V>, position: Vector3<V>) -> Vector3<V> {
        let coefficients = (basis.inverse() * position).rem_euclid(Vector3::ONE);
        basis * coefficients.map(|c| if c >= V::ONE { V::ZERO } else { c })
    }

    /// Returns the shortest representative of `displacement` modulo the
    /// lattice `reduced` spans.
    pub(super) fn nearest<V: Scalar>(reduced: Matrix3<V>, displacement: Vector3<V>) -> Vector3<V> {
        let vectors = [reduced.col(0), reduced.col(1), reduced.col(2)];
        displacement - closest(&vectors, displacement)
    }

    /// Yields the translations of the lattice `reduced` spans that are no
    /// longer than `radius`, the zero vector included, in ascending order of
    /// their coefficients.
    pub(super) fn points<V: Scalar>(
        reduced: Matrix3<V>,
        radius: V,
    ) -> impl Iterator<Item = Vector3<V>> {
        let counts = widths(reduced).recip() * radius;
        let (x, y, z) = (limit(counts.x), limit(counts.y), limit(counts.z));
        let squared = radius * radius;
        (-x..=x)
            .flat_map(move |i| (-y..=y).flat_map(move |j| (-z..=z).map(move |k| (i, j, k))))
            .map(move |(i, j, k)| {
                reduced * Vector3::new(coefficient(i), coefficient(j), coefficient(k))
            })
            .filter(move |point| point.norm_squared() <= squared)
    }

    /// Returns a Minkowski-reduced basis spanning the same lattice as `basis`,
    /// its vectors in ascending length.
    ///
    /// The greedy reduction: reduce the leading pair, then subtract from the
    /// third vector the point of their sublattice [`closest`] to it, and
    /// repeat while that shortens it. Every repetition strictly shortens the
    /// basis, so the descent terminates; in rank three the result realizes the
    /// lattice's successive minima λ₁ ≤ λ₂ ≤ λ₃.
    fn reduce<V: Scalar>(basis: Matrix3<V>) -> Matrix3<V> {
        let mut vectors = [basis.col(0), basis.col(1), basis.col(2)];
        sort_by_length(&mut vectors);
        loop {
            gauss(&mut vectors);
            vectors[2] = vectors[2] - closest(&vectors[..2], vectors[2]);
            if vectors[2].norm_squared() < vectors[1].norm_squared() {
                sort_by_length(&mut vectors);
            } else {
                return Matrix3::from_cols(vectors[0], vectors[1], vectors[2]);
            }
        }
    }

    /// Reduces the leading pair of `vectors` against each other, leaving the
    /// shorter first — the rank-two case of [`reduce`], where the closest
    /// point of a rank-one sublattice is reached by rounding alone.
    fn gauss<V: Scalar>(vectors: &mut [Vector3<V>; 3]) {
        loop {
            if vectors[1].norm_squared() < vectors[0].norm_squared() {
                vectors.swap(0, 1);
            }
            let steps = (vectors[1].dot(vectors[0]) / vectors[0].norm_squared()).round();
            let shortened = vectors[1] - vectors[0] * steps;
            if shortened.norm_squared() < vectors[1].norm_squared() {
                vectors[1] = shortened;
            } else {
                return;
            }
        }
    }

    /// Sorts `vectors` by ascending length.
    fn sort_by_length<V: Scalar>(vectors: &mut [Vector3<V>; 3]) {
        if vectors[1].norm_squared() > vectors[2].norm_squared() {
            vectors.swap(1, 2);
        }
        if vectors[0].norm_squared() > vectors[1].norm_squared() {
            vectors.swap(0, 1);
        }
        if vectors[1].norm_squared() > vectors[2].norm_squared() {
            vectors.swap(1, 2);
        }
    }

    /// Returns the point of the lattice `vectors` span that lies closest to
    /// `target`.
    ///
    /// Fincke–Pohst enumeration: descending to the nearest plane at every
    /// level bounds the distance, and the search then visits every point the
    /// bound cannot rule out. A branch is abandoned only once the orthogonal
    /// components already fixed exceed that distance, which no deeper choice
    /// can undo — so the result is exact whatever basis presents the lattice,
    /// and a poorly conditioned one costs only a wider search.
    fn closest<V: Scalar>(vectors: &[Vector3<V>], target: Vector3<V>) -> Vector3<V> {
        let mut search = Search::new(vectors, target);
        search.approach();
        search.descend(vectors.len() - 1, V::ZERO);
        (0..vectors.len()).fold(Vector3::ZERO, |point, level| {
            point + vectors[level] * search.closest[level]
        })
    }

    /// An enumeration of the lattice points near a target, carried in the
    /// coefficients of the basis it runs over.
    struct Search<V> {
        /// The orthogonalization of the basis.
        orthogonal: [Vector3<V>; 3],
        /// `relation[i][j]`, for `j < i`, is the coefficient of the `j`-th
        /// orthogonal vector in the `i`-th basis vector.
        relation: [[V; 3]; 3],
        /// The squared length of each orthogonal vector.
        squared: [V; 3],
        /// The target in basis coefficients.
        target: [V; 3],
        /// The coefficients of the point under examination.
        trial: [V; 3],
        /// The coefficients of the closest point found so far.
        closest: [V; 3],
        /// The squared distance to that point.
        radius: V,
        /// How many of the three levels the basis spans.
        rank: usize,
    }

    impl<V: Scalar> Search<V> {
        /// Prepares a search over `vectors` for the point closest to `target`,
        /// orthogonalizing the basis and resolving the target against it.
        fn new(vectors: &[Vector3<V>], target: Vector3<V>) -> Self {
            let rank = vectors.len();
            let mut search = Self {
                orthogonal: [Vector3::ZERO; 3],
                relation: [[V::ZERO; 3]; 3],
                squared: [V::ZERO; 3],
                target: [V::ZERO; 3],
                trial: [V::ZERO; 3],
                closest: [V::ZERO; 3],
                radius: V::ZERO,
                rank,
            };
            for (level, &vector) in vectors.iter().enumerate() {
                search.orthogonal[level] = vector;
                for lower in 0..level {
                    search.relation[level][lower] =
                        vector.dot(search.orthogonal[lower]) / search.squared[lower];
                    search.orthogonal[level] -=
                        search.orthogonal[lower] * search.relation[level][lower];
                }
                search.squared[level] = search.orthogonal[level].norm_squared();
            }
            for level in (0..rank).rev() {
                search.target[level] = target.dot(search.orthogonal[level]) / search.squared[level];
                for higher in level + 1..rank {
                    search.target[level] -= search.target[higher] * search.relation[higher][level];
                }
            }
            search
        }

        /// Takes the nearest step at every level, whose distance bounds the
        /// search that follows.
        fn approach(&mut self) {
            let mut distance = V::ZERO;
            for level in (0..self.rank).rev() {
                let center = self.center(level);
                self.trial[level] = center.round();
                let offset = center - self.trial[level];
                distance += offset * offset * self.squared[level];
            }
            self.closest = self.trial;
            self.radius = distance;
        }

        /// Visits every choice at `level` that the distance `reached` by the
        /// levels above leaves room for, keeping the closest point it finds.
        fn descend(&mut self, level: usize, reached: V) {
            let center = self.center(level);
            let half = ((self.radius - reached) / self.squared[level]).sqrt();
            let limit = (center + half).floor();
            let mut step = (center - half).ceil();
            while step <= limit {
                let offset = center - step;
                let extended = reached + offset * offset * self.squared[level];
                if extended < self.radius {
                    self.trial[level] = step;
                    if level == 0 {
                        self.radius = extended;
                        self.closest = self.trial;
                    } else {
                        self.descend(level - 1, extended);
                    }
                }
                step += V::ONE;
            }
        }

        /// The coefficient at which the levels already chosen leave the target
        /// along the `level`-th orthogonal direction.
        fn center(&self, level: usize) -> V {
            (level + 1..self.rank).fold(self.target[level], |center, higher| {
                center + (self.target[higher] - self.trial[higher]) * self.relation[higher][level]
            })
        }
    }

    /// Returns the largest cell offset `count` admits, or `-1` — spanning
    /// nothing — for a count no offset can satisfy.
    ///
    /// A negative count admits none, and neither does one without a bound,
    /// from a radius that is infinite or not a number; refusing both here
    /// keeps the search from saturating into one that would never end.
    fn limit<V: Scalar>(count: V) -> i32 {
        if count >= V::ZERO && count.is_finite() {
            count.floor().to_f64() as i32
        } else {
            -1
        }
    }

    /// Converts a cell offset to a scalar coefficient.
    fn coefficient<V: Scalar>(offset: i32) -> V {
        V::from_f64(f64::from(offset))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::units::angle::Degree;
    use crate::units::length::Nanometer;
    use crate::units::reciprocal_length::ReciprocalNanometer;
    use crate::units::reciprocal_volume::ReciprocalCubicNanometer;

    const TOL: f64 = 1e-9;

    fn length(x: f64) -> Length<f64, Angstrom> {
        Length::new(x)
    }

    fn reciprocal_length(x: f64) -> ReciprocalLength<f64, ReciprocalAngstrom> {
        ReciprocalLength::new(x)
    }

    fn degrees(x: f64) -> Angle<f64, Degree> {
        Angle::new(x)
    }

    fn vector(x: f64, y: f64, z: f64) -> Vector3<Length<f64, Angstrom>> {
        Vector3::new(length(x), length(y), length(z))
    }

    fn wavevector(x: f64, y: f64, z: f64) -> Vector3<ReciprocalLength<f64, ReciprocalAngstrom>> {
        Vector3::new(
            reciprocal_length(x),
            reciprocal_length(y),
            reciprocal_length(z),
        )
    }

    fn position(x: f64, y: f64, z: f64) -> Point3<Length<f64, Angstrom>> {
        Point3::new(length(x), length(y), length(z))
    }

    fn cubic() -> Lattice<f64> {
        Lattice::cubic(length(2.0)).unwrap()
    }

    fn oblique() -> Lattice<f64> {
        Lattice::from_parameters(
            length(3.0),
            length(4.0),
            length(5.0),
            degrees(70.0),
            degrees(80.0),
            degrees(100.0),
        )
        .unwrap()
    }

    fn skewed() -> Lattice<f64> {
        Lattice::from_vectors(
            vector(1.0, 0.0, 0.0),
            vector(0.0, 1.0, 0.0),
            vector(100.0, 0.0, 1.0),
        )
        .unwrap()
    }

    fn length_values<U: LengthUnit>(v: Vector3<Length<f64, U>>) -> [f64; 3] {
        v.to_array().map(|l| l.value())
    }

    fn reciprocal_values<U: ReciprocalLengthUnit>(
        v: Vector3<ReciprocalLength<f64, U>>,
    ) -> [f64; 3] {
        v.to_array().map(|s| s.value())
    }

    fn position_values<U: LengthUnit>(p: Point3<Length<f64, U>>) -> [f64; 3] {
        p.to_array().map(|l| l.value())
    }

    fn angle_values(v: Vector3<Angle<f64, Degree>>) -> [f64; 3] {
        v.to_array().map(|a| a.value())
    }

    fn basis_vectors(lattice: Lattice<f64>) -> [[f64; 3]; 3] {
        [
            length_values(lattice.a::<Angstrom>()),
            length_values(lattice.b::<Angstrom>()),
            length_values(lattice.c::<Angstrom>()),
        ]
    }

    fn oblique_presentations() -> Vec<Lattice<f64>> {
        let mut lattices = Vec::new();
        for alpha in [65.0, 80.0, 95.0, 115.0] {
            for gamma in [70.0, 85.0, 100.0, 130.0] {
                let Some(cell) = Lattice::from_parameters(
                    length(3.0),
                    length(4.0),
                    length(5.0),
                    degrees(alpha),
                    degrees(80.0),
                    degrees(gamma),
                ) else {
                    continue;
                };
                let [a, b, c] = basis_vectors(cell);
                for shear in [0.0, 13.0, 97.0, 1013.0] {
                    let slanted = [0, 1, 2].map(|axis| c[axis] + shear * a[axis]);
                    lattices.push(
                        Lattice::from_vectors(
                            vector(a[0], a[1], a[2]),
                            vector(b[0], b[1], b[2]),
                            vector(slanted[0], slanted[1], slanted[2]),
                        )
                        .unwrap(),
                    );
                }
            }
        }
        lattices
    }

    fn probe_displacements() -> Vec<Vector3<Length<f64, Angstrom>>> {
        let steps = [-1.9, -0.7, 0.4, 1.6];
        (0..4)
            .map(|i| vector(steps[i], steps[(i + 1) % 4], steps[(i + 3) % 4]))
            .collect()
    }

    fn norm(values: [f64; 3]) -> f64 {
        values.iter().map(|value| value * value).sum::<f64>().sqrt()
    }

    fn close(actual: [f64; 3], expected: [f64; 3]) -> bool {
        actual
            .iter()
            .zip(expected.iter())
            .all(|(a, b)| (a - b).abs() < TOL)
    }

    fn exhaustive_minimum_image(
        lattice: Lattice<f64>,
        displacement: Vector3<Length<f64, Angstrom>>,
    ) -> [f64; 3] {
        let basis = basis_vectors(lattice.reduced());
        let target = length_values(displacement);
        let mut shortest = target;
        for i in -3..=3 {
            for j in -3..=3 {
                for k in -3..=3 {
                    let candidate = [0, 1, 2].map(|axis| {
                        target[axis]
                            - f64::from(i) * basis[0][axis]
                            - f64::from(j) * basis[1][axis]
                            - f64::from(k) * basis[2][axis]
                    });
                    if norm(candidate) < norm(shortest) {
                        shortest = candidate;
                    }
                }
            }
        }
        shortest
    }

    fn exhaustive_shortest_vector(lattice: Lattice<f64>) -> f64 {
        let basis = basis_vectors(lattice.reduced());
        let mut shortest = f64::INFINITY;
        for i in -3..=3 {
            for j in -3..=3 {
                for k in -3..=3 {
                    if (i, j, k) == (0, 0, 0) {
                        continue;
                    }
                    let translation = [0, 1, 2].map(|axis| {
                        f64::from(i) * basis[0][axis]
                            + f64::from(j) * basis[1][axis]
                            + f64::from(k) * basis[2][axis]
                    });
                    shortest = shortest.min(norm(translation));
                }
            }
        }
        shortest
    }

    fn assert_close(a: f64, b: f64) {
        assert!((a - b).abs() < TOL, "{a} not close to {b}");
    }

    fn assert_all_close(actual: [f64; 3], expected: [f64; 3]) {
        assert!(
            close(actual, expected),
            "{actual:?} not close to {expected:?}"
        );
    }

    fn assert_integral(coefficients: Point3<f64>) {
        for value in coefficients.to_array() {
            assert_close(value, value.round());
        }
    }

    #[test]
    fn cubic_has_equal_edge_lengths() {
        assert_all_close(length_values(cubic().edge_lengths::<Angstrom>()), [2.0; 3]);
    }

    #[test]
    fn cubic_is_orthogonal() {
        assert_all_close(angle_values(cubic().angles::<Degree>()), [90.0; 3]);
    }

    #[test]
    fn cubic_volume_is_the_side_cubed() {
        assert_close(cubic().volume::<CubicAngstrom>().value(), 8.0);
    }

    #[test]
    fn cubic_basis_vectors_are_axis_aligned() {
        assert_eq!(
            basis_vectors(cubic()),
            [[2.0, 0.0, 0.0], [0.0, 2.0, 0.0], [0.0, 0.0, 2.0]]
        );
    }

    #[test]
    fn orthorhombic_edge_lengths_match_its_arguments() {
        let lattice = Lattice::orthorhombic(length(2.0), length(3.0), length(4.0)).unwrap();
        assert_all_close(
            length_values(lattice.edge_lengths::<Angstrom>()),
            [2.0, 3.0, 4.0],
        );
    }

    #[test]
    fn orthorhombic_volume_is_the_product_of_edges() {
        let lattice = Lattice::orthorhombic(length(2.0), length(3.0), length(4.0)).unwrap();
        assert_close(lattice.volume::<CubicAngstrom>().value(), 24.0);
    }

    #[test]
    fn from_vectors_recovers_its_basis_vectors() {
        let lattice = Lattice::from_vectors(
            vector(2.0, 0.0, 0.0),
            vector(0.0, 3.0, 0.0),
            vector(0.0, 0.0, 4.0),
        )
        .unwrap();
        assert_eq!(
            basis_vectors(lattice),
            [[2.0, 0.0, 0.0], [0.0, 3.0, 0.0], [0.0, 0.0, 4.0]]
        );
    }

    #[test]
    fn from_parameters_reproduces_a_cubic_cell() {
        let lattice = Lattice::from_parameters(
            length(2.0),
            length(2.0),
            length(2.0),
            degrees(90.0),
            degrees(90.0),
            degrees(90.0),
        )
        .unwrap();
        assert_all_close(length_values(lattice.edge_lengths::<Angstrom>()), [2.0; 3]);
        assert_all_close(angle_values(lattice.angles::<Degree>()), [90.0; 3]);
        assert_close(lattice.volume::<CubicAngstrom>().value(), 8.0);
    }

    #[test]
    fn volume_is_the_absolute_value_of_the_determinant() {
        let lattice = Lattice::from_vectors(
            vector(2.0, 0.0, 0.0),
            vector(0.0, 0.0, 3.0),
            vector(0.0, 4.0, 0.0),
        )
        .unwrap();
        assert_close(lattice.volume::<CubicAngstrom>().value(), 24.0);
    }

    #[test]
    fn lattice_vectors_convert_to_the_requested_unit() {
        let lattice = Lattice::cubic(Length::<f64, Nanometer>::new(1.0)).unwrap();
        assert_all_close(length_values(lattice.a::<Angstrom>()), [10.0, 0.0, 0.0]);
    }

    #[test]
    fn to_cartesian_maps_fractional_coordinates_to_positions() {
        let cartesian = cubic().to_cartesian::<Angstrom>(Point3::new(0.5, 0.5, 0.5));
        assert_all_close(position_values(cartesian), [1.0; 3]);
    }

    #[test]
    fn wrap_folds_a_position_outside_the_cell_into_it() {
        let wrapped = cubic().wrap(position(2.5, -0.5, 4.25));
        assert_all_close(position_values(wrapped), [0.5, 1.5, 0.25]);
    }

    #[test]
    fn wrap_leaves_a_position_inside_the_cell_unchanged() {
        let wrapped = cubic().wrap(position(0.5, 1.0, 1.5));
        assert_all_close(position_values(wrapped), [0.5, 1.0, 1.5]);
    }

    #[test]
    fn wrap_of_a_nonfinite_position_is_not_finite() {
        for coordinate in [f64::INFINITY, f64::NAN] {
            let original = position(coordinate, coordinate, coordinate);
            let wrapped = position_values(cubic().wrap(original));
            assert!(wrapped.iter().all(|value| !value.is_finite()));
        }
    }

    #[test]
    fn minimum_image_leaves_a_short_displacement_unchanged() {
        let image = cubic().minimum_image(vector(0.3, -0.4, 0.5));
        assert_all_close(length_values(image), [0.3, -0.4, 0.5]);
    }

    #[test]
    fn minimum_image_shortens_a_displacement_longer_than_half_the_cell() {
        let image = cubic().minimum_image(vector(1.6, -1.4, 0.2));
        assert_all_close(length_values(image), [-0.4, 0.6, 0.2]);
    }

    #[test]
    fn minimum_image_is_exact_for_a_strongly_skewed_cell() {
        let image = skewed().minimum_image(vector(3.4, -2.2, 7.3));
        assert_all_close(length_values(image), [0.4, -0.2, 0.3]);
    }

    #[test]
    fn translations_yield_the_origin_alone_at_zero_radius() {
        let translations: Vec<_> = cubic().translations(length(0.0)).collect();
        assert_eq!(translations.len(), 1);
        assert_all_close(length_values(translations[0]), [0.0; 3]);
    }

    #[test]
    fn translations_yield_the_origin_and_its_six_nearest_neighbors() {
        assert_eq!(cubic().translations(length(2.0)).count(), 7);
    }

    #[test]
    fn translations_yield_nothing_for_a_negative_radius() {
        assert_eq!(cubic().translations(length(-1.0)).count(), 0);
    }

    #[test]
    fn translations_yield_nothing_for_a_nonfinite_radius() {
        assert_eq!(cubic().translations(length(f64::INFINITY)).count(), 0);
        assert_eq!(cubic().translations(length(f64::NAN)).count(), 0);
    }

    #[test]
    fn translations_exclude_vectors_beyond_the_radius() {
        for translation in cubic().translations(length(2.0)) {
            assert!(norm(length_values(translation)) <= 2.0 + TOL);
        }
    }

    #[test]
    fn reduced_leaves_an_already_reduced_lattice_unchanged() {
        assert_eq!(cubic().reduced(), cubic());
    }

    #[test]
    fn reduced_shortens_a_skewed_basis() {
        assert_all_close(
            length_values(skewed().reduced().edge_lengths::<Angstrom>()),
            [1.0; 3],
        );
    }

    #[test]
    fn reduced_edge_lengths_are_the_successive_minima() {
        let lattice = Lattice::orthorhombic(length(4.0), length(2.0), length(3.0)).unwrap();
        assert_all_close(
            length_values(lattice.reduced().edge_lengths::<Angstrom>()),
            [2.0, 3.0, 4.0],
        );
    }

    #[test]
    fn reciprocal_of_a_cubic_lattice_inverts_its_edge_length() {
        assert_all_close(
            reciprocal_values(cubic().reciprocal().edge_lengths::<ReciprocalAngstrom>()),
            [0.5; 3],
        );
    }

    #[test]
    fn reciprocal_vectors_convert_to_the_requested_unit() {
        assert_all_close(
            reciprocal_values(cubic().reciprocal().a::<ReciprocalNanometer>()),
            [5.0, 0.0, 0.0],
        );
    }

    #[test]
    fn reciprocal_volume_is_the_inverse_of_the_cell_volume() {
        let volume = cubic()
            .reciprocal()
            .volume::<ReciprocalCubicAngstrom>()
            .value();
        assert_close(volume, 0.125);
    }

    #[test]
    fn reciprocal_volume_converts_to_the_requested_unit() {
        let volume = cubic()
            .reciprocal()
            .volume::<ReciprocalCubicNanometer>()
            .value();
        assert_close(volume, 125.0);
    }

    #[test]
    fn reciprocal_angles_of_an_orthogonal_cell_are_right() {
        assert_all_close(
            angle_values(cubic().reciprocal().angles::<Degree>()),
            [90.0; 3],
        );
    }

    #[test]
    fn a_reciprocal_lattice_maps_miller_indices_to_a_wavevector() {
        let wavevector = cubic()
            .reciprocal()
            .to_cartesian::<ReciprocalAngstrom>(Point3::new(1.0, 2.0, 0.0));
        assert_all_close(wavevector.to_array().map(|s| s.value()), [0.5, 1.0, 0.0]);
    }

    #[test]
    fn a_reciprocal_lattice_recovers_miller_indices_from_a_wavevector() {
        let reciprocal = cubic().reciprocal();
        let indices = Point3::new(1.0, -2.0, 3.0);
        let recovered =
            reciprocal.to_fractional(reciprocal.to_cartesian::<ReciprocalAngstrom>(indices));
        assert_all_close(recovered.to_array(), indices.to_array());
    }

    #[test]
    fn a_reciprocal_lattice_recovers_its_basis_vectors() {
        let reciprocal = ReciprocalLattice::from_vectors(
            wavevector(0.5, 0.0, 0.0),
            wavevector(0.0, 0.25, 0.0),
            wavevector(0.0, 0.0, 0.2),
        )
        .unwrap();
        assert_all_close(
            reciprocal_values(reciprocal.a::<ReciprocalAngstrom>()),
            [0.5, 0.0, 0.0],
        );
        assert_all_close(
            reciprocal_values(reciprocal.edge_lengths::<ReciprocalAngstrom>()),
            [0.5, 0.25, 0.2],
        );
    }

    #[test]
    fn a_cubic_reciprocal_lattice_has_equal_edge_lengths() {
        let reciprocal = ReciprocalLattice::cubic(reciprocal_length(0.5)).unwrap();
        assert_all_close(
            reciprocal_values(reciprocal.edge_lengths::<ReciprocalAngstrom>()),
            [0.5; 3],
        );
    }

    #[test]
    fn an_orthorhombic_reciprocal_lattice_matches_its_edge_lengths() {
        let reciprocal = ReciprocalLattice::orthorhombic(
            reciprocal_length(0.5),
            reciprocal_length(0.25),
            reciprocal_length(0.2),
        )
        .unwrap();
        assert_all_close(
            reciprocal_values(reciprocal.edge_lengths::<ReciprocalAngstrom>()),
            [0.5, 0.25, 0.2],
        );
    }

    #[test]
    fn a_reciprocal_lattice_from_parameters_reproduces_a_cubic_cell() {
        let reciprocal = ReciprocalLattice::from_parameters(
            reciprocal_length(0.5),
            reciprocal_length(0.5),
            reciprocal_length(0.5),
            degrees(90.0),
            degrees(90.0),
            degrees(90.0),
        )
        .unwrap();
        assert_all_close(
            reciprocal_values(reciprocal.edge_lengths::<ReciprocalAngstrom>()),
            [0.5; 3],
        );
        assert_all_close(angle_values(reciprocal.angles::<Degree>()), [90.0; 3]);
    }

    #[test]
    fn a_reciprocal_lattice_wraps_a_wavevector_into_its_cell() {
        let reciprocal = ReciprocalLattice::cubic(reciprocal_length(0.5)).unwrap();
        let wrapped = reciprocal.wrap(Point3::new(
            reciprocal_length(0.6),
            reciprocal_length(-0.1),
            reciprocal_length(0.25),
        ));
        assert_all_close(wrapped.to_array().map(|s| s.value()), [0.1, 0.4, 0.25]);
    }

    #[test]
    fn a_reciprocal_lattice_folds_a_displacement_into_the_first_brillouin_zone() {
        let reciprocal = ReciprocalLattice::cubic(reciprocal_length(0.5)).unwrap();
        let image = reciprocal.minimum_image(wavevector(0.4, -0.35, 0.1));
        assert_all_close(reciprocal_values(image), [-0.1, 0.15, 0.1]);
    }

    #[test]
    fn a_reciprocal_lattice_yields_the_origin_and_its_six_nearest_neighbors() {
        let reciprocal = ReciprocalLattice::cubic(reciprocal_length(0.5)).unwrap();
        assert_eq!(reciprocal.translations(reciprocal_length(0.5)).count(), 7);
    }

    #[test]
    fn a_reciprocal_lattice_reduces_to_its_successive_minima() {
        let reciprocal = ReciprocalLattice::orthorhombic(
            reciprocal_length(0.4),
            reciprocal_length(0.2),
            reciprocal_length(0.3),
        )
        .unwrap();
        assert_all_close(
            reciprocal_values(reciprocal.reduced().edge_lengths::<ReciprocalAngstrom>()),
            [0.2, 0.3, 0.4],
        );
    }

    #[test]
    fn cubic_rejects_a_zero_side() {
        assert!(Lattice::cubic(length(0.0)).is_none());
    }

    #[test]
    fn cubic_rejects_a_nonfinite_side() {
        assert!(Lattice::cubic(length(f64::INFINITY)).is_none());
        assert!(Lattice::cubic(length(f64::NAN)).is_none());
    }

    #[test]
    fn orthorhombic_rejects_a_nonpositive_edge() {
        assert!(Lattice::orthorhombic(length(0.0), length(3.0), length(4.0)).is_none());
        assert!(Lattice::orthorhombic(length(2.0), length(-3.0), length(4.0)).is_none());
    }

    #[test]
    fn from_vectors_rejects_coplanar_vectors() {
        let lattice = Lattice::from_vectors(
            vector(1.0, 0.0, 0.0),
            vector(0.0, 1.0, 0.0),
            vector(1.0, 1.0, 0.0),
        );
        assert!(lattice.is_none());
    }

    #[test]
    fn from_vectors_rejects_a_cell_too_thin_to_resolve() {
        let lattice = Lattice::from_vectors(
            vector(1.0, 0.0, 0.0),
            vector(0.0, 1.0, 0.0),
            vector(0.0, 0.0, 1e-200),
        );
        assert!(lattice.is_none());
    }

    #[test]
    fn from_parameters_rejects_a_nonpositive_edge() {
        let lattice = Lattice::from_parameters(
            length(0.0),
            length(2.0),
            length(2.0),
            degrees(90.0),
            degrees(90.0),
            degrees(90.0),
        );
        assert!(lattice.is_none());
    }

    #[test]
    fn from_parameters_rejects_an_unrealizable_cell() {
        let lattice = Lattice::from_parameters(
            length(2.0),
            length(2.0),
            length(2.0),
            degrees(170.0),
            degrees(170.0),
            degrees(170.0),
        );
        assert!(lattice.is_none());
    }

    #[test]
    fn a_reciprocal_lattice_rejects_a_nonpositive_edge() {
        assert!(ReciprocalLattice::cubic(reciprocal_length(0.0)).is_none());
        assert!(
            ReciprocalLattice::orthorhombic(
                reciprocal_length(0.5),
                reciprocal_length(-0.25),
                reciprocal_length(0.2)
            )
            .is_none()
        );
    }

    #[test]
    fn a_reciprocal_lattice_rejects_coplanar_vectors() {
        let reciprocal = ReciprocalLattice::from_vectors(
            wavevector(1.0, 0.0, 0.0),
            wavevector(0.0, 1.0, 0.0),
            wavevector(1.0, 1.0, 0.0),
        );
        assert!(reciprocal.is_none());
    }

    #[test]
    fn from_parameters_roundtrips_edge_lengths_and_angles() {
        let lattice = oblique();
        assert_all_close(
            length_values(lattice.edge_lengths::<Angstrom>()),
            [3.0, 4.0, 5.0],
        );
        assert_all_close(
            angle_values(lattice.angles::<Degree>()),
            [70.0, 80.0, 100.0],
        );
    }

    #[test]
    fn to_fractional_inverts_to_cartesian() {
        let lattice = oblique();
        let fractional = Point3::new(0.1, 0.2, 0.7);
        let recovered = lattice.to_fractional(lattice.to_cartesian::<Angstrom>(fractional));
        assert_all_close(recovered.to_array(), fractional.to_array());
    }

    #[test]
    fn wrap_is_idempotent() {
        let lattice = oblique();
        let once = lattice.wrap(position(7.3, -4.1, 2.6));
        assert_all_close(position_values(lattice.wrap(once)), position_values(once));
    }

    #[test]
    fn wrap_keeps_the_fractional_coordinates_below_one() {
        let lattice = cubic();
        let wrapped = lattice.wrap(position(-1e-20, -1e-20, -1e-20));
        for coefficient in lattice.to_fractional::<Angstrom>(wrapped).to_array() {
            assert!((0.0..1.0).contains(&coefficient));
        }
    }

    #[test]
    fn wrap_differs_from_its_argument_by_a_lattice_vector() {
        let lattice = oblique();
        let original = position(7.3, -4.1, 2.6);
        let displacement = lattice.wrap(original) - original;
        assert_integral(lattice.to_fractional::<Angstrom>(Point3::from_vector(displacement)));
    }

    #[test]
    fn minimum_image_agrees_with_an_exhaustive_search() {
        for lattice in oblique_presentations() {
            for displacement in probe_displacements() {
                assert_all_close(
                    length_values(lattice.minimum_image(displacement)),
                    exhaustive_minimum_image(lattice, displacement),
                );
            }
        }
    }

    #[test]
    fn minimum_image_differs_from_its_argument_by_a_lattice_vector() {
        let lattice = oblique();
        let original = vector(1.4, -2.6, 3.1);
        let displacement = lattice.minimum_image(original) - original;
        assert_integral(lattice.to_fractional::<Angstrom>(Point3::from_vector(displacement)));
    }

    #[test]
    fn minimum_image_is_independent_of_the_presenting_basis() {
        let sheared = Lattice::from_vectors(
            vector(2.0, 0.0, 0.0),
            vector(0.0, 2.0, 0.0),
            vector(2.0, 0.0, 2.0),
        )
        .unwrap();
        let displacement = vector(1.6, 1.4, 0.9);
        assert_all_close(
            length_values(sheared.minimum_image(displacement)),
            length_values(cubic().minimum_image(displacement)),
        );
    }

    #[test]
    fn translations_are_closed_under_negation() {
        let lattice = oblique();
        let translations: Vec<_> = lattice
            .translations(length(6.0))
            .map(length_values)
            .collect();
        for translation in &translations {
            let negated = translation.map(|value| -value);
            assert!(translations.iter().any(|other| close(*other, negated)));
        }
    }

    #[test]
    fn translations_are_independent_of_the_presenting_basis() {
        let sheared = Lattice::from_vectors(
            vector(2.0, 0.0, 0.0),
            vector(0.0, 2.0, 0.0),
            vector(2.0, 0.0, 2.0),
        )
        .unwrap();
        let expected: Vec<_> = cubic()
            .translations(length(3.0))
            .map(length_values)
            .collect();
        let actual: Vec<_> = sheared
            .translations(length(3.0))
            .map(length_values)
            .collect();
        assert_eq!(actual.len(), expected.len());
        for translation in &actual {
            assert!(expected.iter().any(|other| close(*other, *translation)));
        }
    }

    #[test]
    fn reduced_is_idempotent() {
        let reduced = skewed().reduced();
        assert_eq!(reduced.reduced(), reduced);
    }

    #[test]
    fn reduced_begins_with_the_shortest_lattice_vector() {
        for lattice in oblique_presentations() {
            let shortest = length_values(lattice.reduced().edge_lengths::<Angstrom>())[0];
            assert_close(shortest, exhaustive_shortest_vector(lattice));
        }
    }

    #[test]
    fn reduced_spans_the_same_lattice() {
        for lattice in oblique_presentations() {
            let reduced = lattice.reduced();
            assert_close(
                reduced.volume::<CubicAngstrom>().value(),
                lattice.volume::<CubicAngstrom>().value(),
            );
            for basis_vector in basis_vectors(lattice) {
                let point = Point3::new(
                    length(basis_vector[0]),
                    length(basis_vector[1]),
                    length(basis_vector[2]),
                );
                assert_integral(reduced.to_fractional::<Angstrom>(point));
            }
        }
    }

    #[test]
    fn reciprocal_vectors_are_dual_to_the_basis_vectors() {
        let lattice = oblique();
        let reciprocal = lattice.reciprocal();
        let direct = basis_vectors(lattice).map(Vector3::from_array);
        let dual = [
            reciprocal.a::<ReciprocalAngstrom>(),
            reciprocal.b::<ReciprocalAngstrom>(),
            reciprocal.c::<ReciprocalAngstrom>(),
        ]
        .map(|v| Vector3::from_array(reciprocal_values(v)));
        for (i, row) in direct.iter().enumerate() {
            for (j, column) in dual.iter().enumerate() {
                assert_close(row.dot(*column), if i == j { 1.0 } else { 0.0 });
            }
        }
    }

    #[test]
    fn reciprocal_of_the_reciprocal_recovers_the_lattice() {
        let lattice = oblique();
        let recovered = lattice.reciprocal().reciprocal();
        for (actual, expected) in basis_vectors(recovered)
            .iter()
            .zip(basis_vectors(lattice).iter())
        {
            assert_all_close(*actual, *expected);
        }
    }

    #[test]
    fn reciprocal_edge_lengths_invert_the_perpendicular_widths() {
        let lattice = oblique();
        let [a, b, c] = basis_vectors(lattice).map(Vector3::from_array);
        let volume = lattice.volume::<CubicAngstrom>().value();
        let widths = [
            volume / b.cross(c).norm(),
            volume / c.cross(a).norm(),
            volume / a.cross(b).norm(),
        ];
        assert_all_close(
            reciprocal_values(lattice.reciprocal().edge_lengths::<ReciprocalAngstrom>()),
            widths.map(|width| 1.0 / width),
        );
    }

    #[test]
    fn the_operations_are_generic_over_f32() {
        let lattice = Lattice::cubic(Length::<f32, Angstrom>::new(2.0)).unwrap();
        let image = lattice.minimum_image(Vector3::new(
            Length::<f32, Angstrom>::new(1.5),
            Length::new(0.25),
            Length::new(0.0),
        ));
        assert_eq!(image.to_array().map(|l| l.value()), [-0.5, 0.25, 0.0]);
        let spacings = lattice.reciprocal().edge_lengths::<ReciprocalAngstrom>();
        assert_eq!(spacings.to_array().map(|s| s.value()), [0.5; 3]);
    }
}
