name: Task
description: A specific piece of work or maintenance.
type: Task
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done and why?
    validations:
      required: true

  - type: textarea
    id: criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this task is complete?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
    validations:
      required: false
