[package]
name = "vita-core"
version = "0.2.0"
description = "Zero-dependency primitives for atomistic and molecular computation."
keywords = [
    "atomistic",
    "molecular",
    "bioinformatics",
    "cheminformatics",
    "biochemistry",
]
categories = [
    "science",
    "science::computational-biology",
    "science::computational-chemistry",
    "science::materials",
    "mathematics",
]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "vita_core"
path = "src/lib.rs"
